/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package systest;

import java.sql.ResultSet;
import java.sql.SQLException;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.JFrame;

/**
 *
 * @author ilyas
 */
public class login_Rasp extends javax.swing.JFrame {

    /**
     * Creates new form login
     */
    public login_Rasp() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel1 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        usernamefield = new javax.swing.JTextField();
        jLabel5 = new javax.swing.JLabel();
        passfield = new javax.swing.JPasswordField();
        loginbtn = new javax.swing.JButton();
        errorfield = new javax.swing.JLabel();
        loginbtn1 = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("hospitalSys | Login");
        setResizable(false);
        getContentPane().setLayout(null);

        jLabel2.setFont(new java.awt.Font("Lucida Grande", 1, 36)); // NOI18N
        jLabel2.setForeground(new java.awt.Color(0, 102, 204));
        jLabel2.setText("System");
        getContentPane().add(jLabel2);
        jLabel2.setBounds(140, 80, 150, 47);

        jLabel3.setFont(new java.awt.Font("Corporate A", 1, 36)); // NOI18N
        jLabel3.setForeground(new java.awt.Color(0, 102, 204));
        jLabel3.setText("Hospital Management");
        getContentPane().add(jLabel3);
        jLabel3.setBounds(40, 30, 380, 60);

        jLabel1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/hospitalSys/images/entrance1.jpg"))); // NOI18N
        getContentPane().add(jLabel1);
        jLabel1.setBounds(0, 0, 480, 170);

        jLabel4.setText("Username");
        getContentPane().add(jLabel4);
        jLabel4.setBounds(100, 190, 90, 16);
        getContentPane().add(usernamefield);
        usernamefield.setBounds(100, 210, 290, 40);

        jLabel5.setText("Password");
        getContentPane().add(jLabel5);
        jLabel5.setBounds(100, 260, 90, 16);
        getContentPane().add(passfield);
        passfield.setBounds(100, 280, 290, 40);

        loginbtn.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        loginbtn.setText("Login");
        loginbtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                loginbtnActionPerformed(evt);
            }
        });
        getContentPane().add(loginbtn);
        loginbtn.setBounds(100, 350, 290, 40);

        errorfield.setForeground(new java.awt.Color(204, 0, 0));
        getContentPane().add(errorfield);
        errorfield.setBounds(100, 390, 290, 20);

        loginbtn1.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        loginbtn1.setText("Register");
        loginbtn1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                loginbtn1ActionPerformed(evt);
            }
        });
        getContentPane().add(loginbtn1);
        loginbtn1.setBounds(100, 410, 290, 40);

        setSize(new java.awt.Dimension(462, 505));
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void loginbtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_loginbtnActionPerformed
        String Username = usernamefield.getText().toString();
        String Password = passfield.getText().toString();
               
        //Using RASP to detect zero-day attack
        if (isSQLInjection(Username) || isSQLInjection(Password)) {
            System.out.println("Potential SQL Injection detected!");
        } else {
        
            //Authenticated for login activities
            String TABLE_NAME = "users";

            ResultSet rs = Connect.Select_request("SELECT * FROM "+TABLE_NAME+" WHERE username = '"+Username+"' and password = '"+Password+"'");

            try {
                if (rs.next()){
                    int id = rs.getInt("emp_no");
                    JFrame mainapp = new mainapp(id);
                    mainapp.setVisible(true);
                    this.setVisible(false);
                }else {
                    errorfield.setText("Wrong Username/Password combination !");

                }
            } catch (SQLException ex) {
                Logger.getLogger(login_Rasp.class.getName()).log(Level.SEVERE, null, ex);
            }
            
         } //end if
        
                
                
    }//GEN-LAST:event_loginbtnActionPerformed

    private static boolean isSQLInjection(String input) {
        // Simple pattern matching to detect SQL injection. Below are examples of malicious input 
        String[] sqlInjectionPatterns = {"'","1", "1=1", "\"", ";", "--", "/*", "*/", " OR ", " AND "};
        for (String pattern : sqlInjectionPatterns) {
            if (input.contains(pattern)) {
                return true;
            }
        }
        return false;
    }
    
    private void loginbtn1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_loginbtn1ActionPerformed
       
    }//GEN-LAST:event_loginbtn1ActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Mac Os".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(login_Rasp.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(login_Rasp.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(login_Rasp.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(login_Rasp.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new login_Rasp().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel errorfield;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JButton loginbtn;
    private javax.swing.JButton loginbtn1;
    private javax.swing.JPasswordField passfield;
    private javax.swing.JTextField usernamefield;
    // End of variables declaration//GEN-END:variables
}
